#!/usr/bin/python

import util
import pickle
import argparse

def summarise(model, limit = None):
    print 'C major matrix:'
    model[0].print_summary(limit)
    print '\nC minor matrix:'
    model[12].print_summary(limit)

if __name__ == '__main__':
    parser = argparse.ArgumentParser(description = 'Key detector model inspector')
    parser.add_argument('-m', '--model', default = 'model.pkl')
    parser.add_argument('--limit', default = 20, type = int)
    args = parser.parse_args()

    with open(args.model, 'rb') as f:
        model = pickle.load(f)

    summarise(model, args.limit)
