#!/usr/bin/python

import argparse
import pickle

from keydetection import *

def summarise(model, limit = None):
    print 'C major matrix:'
    model[0].print_summary(limit)
    print '\nC minor matrix:'
    model[12].print_summary(limit)

if __name__ == '__main__':
    parser = argparse.ArgumentParser(description = 'Key detector model inspector')
    parser.add_argument('-m', '--model', default = 'model.pkl')
    parser.add_argument('--limit', default = 20, type = int)
    args = parser.parse_args()

    if args.model == '__pitch_classes__':
        model = get_pitch_class_model()
    else:
        model = pickle.load(open(args.model))
    summarise(model, args.limit)
