#!/usr/bin/env python

import pickle
import argparse

from keydetection import *

Cache.set_caching_read(False)
Cache.set_caching_write(False)

def getkey(model, wav_filename, output_filename):

    model = normalise_model(model, True)
    test_profile = get_test_profile(wav_filename)
    key = get_key(model, test_profile)
    with open(output_filename, 'w') as f:
        f.write('%s\n' % key.mirex_repr())

if __name__ == '__main__':
    parser = argparse.ArgumentParser(description = 'MIREX-formatted key detection')
    parser.add_argument('-m', '--model', default = 'model.pkl')
    parser.add_argument('-v', '--verbose', action = 'store_true', default = False)
    parser.add_argument('-i', '--input', required = True, help = 'Wav filename')
    parser.add_argument('-o', '--output', required = True, help = 'Output filename')
    args = parser.parse_args()

    if args.verbose:
        logging.basicConfig(level = logging.DEBUG)

    with open(args.model, 'rb') as f:
        model = pickle.load(f)

    getkey(model, args.input, args.output)
