#!/usr/bin/python

# TODO: multitread

import util
import argparse
import pickle

def train(mp3dir, labdir, limit = None):
    training_filenames = util.filenames_from_twin_directories(mp3dir, labdir, limit)
    training_matrices = util.get_aggregate_markov_matrices(training_filenames)
    return training_matrices

if __name__ == '__main__':
    parser = argparse.ArgumentParser(description = 'Train key detector')
    parser.add_argument('-m', '--mp3dir', required = True)
    parser.add_argument('-l', '--labdir', required = True)
    parser.add_argument('-o', '--outfile', default = 'model.pkl')
    parser.add_argument('--limit', type = int)
    args = parser.parse_args()
    matrices = train(args.mp3dir, args.labdir, args.limit)
    with open(args.outfile, 'wb') as outfile:
        pickle.dump(matrices, outfile)
